# 모델링 관련 

data:
  # 전처리된 데이터가 저장된 디렉토리 (result에 저장)
  processed_data_dir: "result"
  train_data_file: "tmdb_train.csv"
  test_data_file: "tmdb_test.csv"
  feature_names_file: "feature_names.json"

model:
  output_dir: "model_artifacts" 
  filename: "xgboost_movie_rating_model.pkl"
  target_column: "vote_average" 
  xgboost_params:
    objective: "reg:squarederror" 
    n_estimators: 1000 
    learning_rate: 0.05 
    max_depth: 6 
    subsample: 0.7 
    colsample_bytree: 0.7 
    random_state: 42 
    n_jobs: -1 

mlflow:
  tracking_uri: "http://localhost:5000" 
  model_registry_name: "MovieRatingXGBoostModel" 
  experiment_name: "Movie-Rating-Prediction"